[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ksg_nft = "67uqmtwUpEk6w8Nnopv3FoZxs3j2stbbKqabE3wNGbZ1"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "/home/whitehorse/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
